std_msgs/Header                 header
Oem7Header                      nov_header
SolutionStatus                  sol_status
PositionOrVelocityType          pos_type
float64                         lat
float64                         lon
float64                         hgt
float32                         undulation
uint32                          datum_id
float32                         lat_stdev
float32                         lon_stdev
float32                         hgt_stdev
int8[4]                         stn_id
float32                         diff_age
float32                         sol_age
uint8                           num_svs
uint8                           num_sol_svs
uint8                           num_sol_l1_svs
uint8                           num_sol_multi_svs
uint8                           reserved
BestExtendedSolutionStatus      ext_sol_stat
uint8                           galileo_beidou_sig_mask
uint8                           gps_glonass_sig_mask






