std_msgs/Header     header
Oem7Header          nov_header
uint32              imu_type
uint8               mapping
uint8               initial_alignment_velocity
uint16              heave_window
uint32              profile
uint8[4]            enabled_updates
INSAlignmentMode    alignment_mode
INSOutputFrame      relative_ins_output_frame
bool                relative_ins_output_direction
INSReceiverStatus   ins_receiver_status
uint8               ins_seed_enabled
uint8               ins_seed_validation
uint16              reserved_1
uint32              reserved_2
uint32              reserved_3
uint32              reserved_4
uint32              reserved_5
uint32              reserved_6
uint32              reserved_7
uint32              number_of_translations
Translation[]       translations
uint32              number_of_rotations
Rotation[]          rotations







         
