uint8 INITIALIZED                     = 0
uint8 INS_TIMING_ERROR                = 1
uint8 INVALID_SOLUTION                = 2
uint8 INS_ORIENT_CHANGED              = 3
uint8 INS_USER_COMMAND                = 4
uint8 INS_CALIBRATION                 = 5
uint8 INIT_ATTITUDE_RECEIVED          = 6
uint8 ALIGNMENT_MODE_CHANGED          = 8
uint8 EXPT_RESTRICTS_EXCEEDED         = 9
uint8 DATA_GAP                        = 10
uint8 RECEIVED_IMU_SPECS              = 11
uint8 ACCEL_RESTRICTIONS_EXCEEDED     = 12
uint8 ROTATION_RESTRICTIONS_EXCEEDED  = 13
uint8 RAWIMU_STATUS_INVALID           = 14
uint8 IMU_CONFIGURED                  = 15
uint8 IMU_UNUSPPORTED                 = 16
uint8 INS_SEED_INVALID                = 17
uint8 INS_SEED_VALIDATION_FAILED      = 18
uint8 USER_COMMAND_RESTART            = 19

uint8 type