std_msgs/Header                 header
Oem7Header                      nov_header
SolutionStatus                  p_sol_status
PositionOrVelocityType          pos_type
float64                         p_x
float64                         p_y
float64                         p_z
float32                         p_x_stdev
float32                         p_y_stdev
float32                         p_z_stdev
SolutionStatus                  v_sol_status
PositionOrVelocityType          vel_type
float64                         v_x
float64                         v_y
float64                         v_z
float32                         v_x_stdev
float32                         v_y_stdev
float32                         v_z_stdev
int8[4]                         stn_id
float32                         v_latency
float32                         diff_age
float32                         sol_age
uint8                           num_svs
uint8                           num_sol_svs
BestExtendedSolutionStatus      ext_sol_stat
uint8                           galileo_beidou_sig_mask
uint8                           gps_glonass_sig_mask







