uint32 RESERVED_1                = 511             # 0x000001FF
uint32 TERRASTAR_C_SERVICE       = 512             # 0x00000200
uint32 TERRASTAR_L_SERVICE       = 1024            # 0x00000400
uint32 RTK_ASSIST_SERVICE        = 2048            # 0x00000800
uint32 RTK_ASSIST_PRO_SERVICE    = 4096            # 0x00001000
uint32 TERRASTAR_C_PRO_SERVICE   = 8192            # 0x00002000
uint32 TERRASTAR_X_SERVICE       = 16384           # 0x00004000
uint32 RESERVED_2                = 4294934528      # 0xFFFF8000


uint32 permission