Header                          header
Oem7Header                      nov_header
string                          product_activation_code
SubscriptionType                sub_type
SubscriptionPermission          sub_permission
uint32                          service_end_day_of_year
uint32                          service_end_year
uint32                          reserved
RegionRestriction               region_restriction
float32                         center_point_latitude
float32                         center_point_longitude
uint32                          radius







