from ros:noetic

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y vim sudo  

#----------------------------------
# Create 'test:test' user/password in sudo group.
RUN useradd -m test && echo "test:test" | chpasswd && adduser test sudo
USER test
#----------------------------------


# If no command is provided when the container is started, this will be run, giving you a shell inside the container as the 'test' user.
CMD "/bin/bash"
